version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: bd-clientes-pedidos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgresdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: npm run dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/bd-clientes-pedidos

volumes:
  postgresdata:
