apiVersion: v1
kind: Pod
metadata:
  name: producao-main-pod
  labels:
    app: node
    tier: producao
    role: main
spec:
  containers:
    - name: producao-main-container
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
